---
title: "Research"
sidebar: false
---

## Current research profile  

The core of my research program investigates model validation and inference in the context of statistical machine learning. As scientists fit increasingly complex models to their data, there is an ever-growing need for methods that quantify our uncertainty in the quality of these models, and for methods that can formally test  results suggested by these models. My work seeks to fill this gap, especially within the context of unsupervised learning, where existing methods for validation and inference are limited compared to the supervised learning setting. My research program has expanded our statistical toolkit for using a single data set to  fit a supervised or unsupervised learning model and to (1) test hypotheses suggested by that fitted model, (2) assess the stability of that fitted model, or (3) accurately estimate the prediction error of that fitted model. The methods developed in the course of my research program are relevant to many application domains, and have particular impact in the field of single-cell genomics, where the output of unsupervised learning models are routinely used as surrogates for unobserved aspects of cell states. 

I have secondary interests in developing theory and methodology in the area of optimal experiment design and the selection of hyperparameters for statistical machine learning algorithms. These diverse areas are unified by my interest in adapting key ideas from the mathematical optimization community to statistical problems. 

## Publications

In the following, \* represents alphabetical author ordering.

## Pre-prints 
Yiqun T. Chen and **Lucy L. Gao**. Testing for a difference in means of a single feature after clustering. [[pdf](https://arxiv.org/pdf/2311.16375.pdf)]

**Lucy L. Gao**\*, Jane J. Ye\*, Haian Yin\*, Shangzhi Zeng\*, and Jin Zhang\*. Moreau Envelope Based Difference-of-weakly-Convex Reformulation and Algorithm for Bilevel Programs. [[pdf](https://arxiv.org/abs/2306.16761)]

Abigail Keller, **Lucy L. Gao**, Daniela Witten, and Maitreya J. Dunham. Condition-dependent fitness effects of large synthetic chromosome amplifications. [[pdf](https://www.biorxiv.org/content/10.1101/2023.06.08.544269v1)]



## Accepted

Ameer Dharamshi, Anna Neufeld, Keshav Motwani, **Lucy L. Gao**, Daniela Witten, and Jacob Bien (2024+). Generalized data thinning using sufficient statistics. To appear in *Journal of the Americal Statistical Association*. [[pdf](https://arxiv.org/abs/2303.12931)]

Anna Neufeld, Ameer Dharamshi, **Lucy L. Gao**, and Daniela Witten (2024+) Data thinning for convolution-closed distributions. To appear in *Journal of Machine Learning Research*. [[pdf](https://arxiv.org/abs/2301.07276)] [[software](https://anna-neufeld.github.io/datathin/index.html)]

**Lucy L. Gao**\*, Jane J. Ye\*, Shangzhi Zeng\*, and Julie Zhou\* (2024+) Necessary and sufficient conditions for multiple objective optimal regression designs. To appear in *Statistica Sinica*.  [[pdf](https://arxiv.org/abs/2303.04746)][[code](https://github.com/lucylgao/multi-objective-paper-code-2022)]

## 2024 

**Lucy L. Gao**, Jacob Bien, and Daniela Witten (2024) Selective inference for hierarchical clustering. *Journal of the American Statistical Association*, 119(545), 332-342. [[pdf](https://arxiv.org/abs/2012.02936)] [[software](clusterpval)]

Anna Neufeld, **Lucy L. Gao**, Joshua Popp, Alexis Battle, and Daniela Witten (2024) Inference after latent variable estimation for single-cell RNA-sequencing data. *Biostatistics*, 25(1), 270-287. [[pdf](https://arxiv.org/abs/2207.00554)] [[software](https://anna-neufeld.github.io/countsplit/)]

## 2022 

Anna Neufeld, **Lucy L. Gao**, and Daniela Witten (2022) Tree-values: selective inference for regression trees. *Journal of Machine Learning Research*, 23(305), 1−43. [[pdf](https://arxiv.org/pdf/2106.07816.pdf)] [[software](https://anna-neufeld.github.io/treevalues/)]

**Lucy L. Gao**, Daniela Witten and Jacob Bien (2022) Testing for association in multi-view network data. *Biometrics*, 78(3), 1018-1030. [[pdf](https://arxiv.org/pdf/1909.11640)] [[software](https://cran.r-project.org/web/packages/multiviewtest/index.html)]

**Lucy L. Gao**\*, Jane J. Ye\*, Haian Yin\*, Shangzhi Zeng\*, and Jin Zhang\* (2022). Value function based difference-of-convex algorithm for bilevel hyperparameter selection problems. *Proceedings of International Conference on Machine Learning (ICML) 2022*. [[pdf](https://arxiv.org/abs/2206.05976)] [[code](https://github.com/SUSTech-Optimization/VF-iDCA)]

Pengqi Liu, **Lucy L. Gao** and Julie Zhou (2022). R-optimal designs for multi-response regression models with multi-factors. *Communications in Statistics - Theory and Methods*, 51(2), 340-355. [[pdf](https://arxiv.org/abs/1910.02539)]

## 2020

**Lucy L. Gao**, Jacob Bien and Daniela Witten (2020). Are clusterings of multiple data views independent? Biostatistics, 21(4), 692-708. [[pdf](https://arxiv.org/abs/1901.03905)] [[software](https://cran.r-project.org/web/packages/multiviewtest/index.html)]

**Lucy L. Gao** and Julie Zhou (2020). Minimax D-optimal designs for multivariate regression models with multi-factors. *Journal of Statistical Planning and Inference*.  [[pdf](https://arxiv.org/abs/1910.00745)]

## 2015-2019

Evelyn Hsu, Michele Shaffer, **Lucy L. Gao**, Christopher Sonnenday, Michael Volk, John Bucuvalas, and Jennifer Lai (2017).
Analysis of liver offers to pediatric candidates on the transplant wait list. *Gastroenterology*, 153 (4), 998-995. 

**Lucy L. Gao**\* and Julie Zhou\* (2017). D-optimal designs based on the second-order least squares estimator. *Statistical Papers*, 58(2), 77-94. [[pdf](https://dspace.library.uvic.ca:8443/handle/1828/7383)]

**Lucy L. Gao** and Julie Zhou (2014) New optimal design criteria for regression models with asymmetric errors. *Journal of Statistical Planning and Inference*, 149: 140-151.
